name: Publish Runtime

on:
  push:
    branches:
      - main
    tags:        
      - 'runtime-*.*.*'
    paths-ignore:
      - 'src/**'
      - 'tests/**'
      - 'samples/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install minver
        run: dotnet tool install --global minver-cli --version 6.0.0
      - uses: nuget/setup-nuget@v2
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-version: '5.x'
      - name: Compute version and pack
        run: |
          version=$(minver -v e -t runtime-)
          nuget pack packages-definitions/libtreesitter/libtreesitter.nuspec -Properties version=$version
          nuget pack packages-definitions/libtreesitter.runtime.linux-x64/libtreesitter.runtime.linux-x64.nuspec -Properties version=$version 
      - name: Publish libtreesitter package to Nuget
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
