name: Publish TreeSitter

on:
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Pack libtreesitter
        run: nuget pack tree-sitter-packages/libtreesitter/libtreesitter.nuspec
      - name: Pack libtreesitter.runtime.linux-x64
        run: nuget pack tree-sitter-packages/libtreesitter.runtime.linux-x64/libtreesitter.runtime.linux-x64.nuspec  
      - name: Publish libtreesitter package to GHR
        run: dotnet nuget push *.nupkg  --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"
